/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // === Material 3 dark palette (із Stitch) ===
        background: "#10131a",
        "on-background": "#e1e2ec",
        surface: "#10131a",
        "on-surface": "#e1e2ec",
        "surface-variant": "#32353c",
        "on-surface-variant": "#c2c6d6",
        "surface-dim": "#10131a",
        "surface-bright": "#363941",
        "surface-container-lowest": "#0b0e15",
        "surface-container-low": "#191b23",
        "surface-container": "#1d2027",
        "surface-container-high": "#272a31",
        "surface-container-highest": "#32353c",
        outline: "#8c909f",
        "outline-variant": "#424754",
        primary: "#adc6ff",
        "on-primary": "#002e6a",
        "primary-container": "#4d8eff",
        "on-primary-container": "#00285d",
        "primary-fixed": "#d8e2ff",
        "primary-fixed-dim": "#adc6ff",
        secondary: "#4ae176",
        "on-secondary": "#003915",
        "secondary-container": "#00b954",
        "on-secondary-container": "#004119",
        "secondary-fixed": "#6bff8f",
        "secondary-fixed-dim": "#4ae176",
        tertiary: "#ffb786",
        "on-tertiary": "#502400",
        "tertiary-container": "#df7412",
        "on-tertiary-container": "#461f00",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "inverse-surface": "#e1e2ec",
        "inverse-on-surface": "#2e3038",
        "inverse-primary": "#005ac2",
        "surface-tint": "#adc6ff",
        // === Aliases (для нашої доменної моделі) ===
        ok: "#4ae176",
        okContainer: "#00b954",
        warn: "#df7412",
        warnContainer: "#df7412",
        crit: "#ffb4ab",
        critContainer: "#93000a",
        rescue: "#9b59b6",
        text: "#e1e2ec",
        muted: "#c2c6d6",
        border: "#424754",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "16px",
        "component-gap": "12px",
        "container-padding": "24px",
        "mobile-margin": "16px",
        "desktop-margin": "32px",
        unit: "4px",
      },
      fontFamily: {
        body: ["Inter", "system-ui", "sans-serif"],
        display: ["DM Sans", "Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        // Для зручності зроблено aliasи, як у Stitch:
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "display-lg": ["DM Sans", "sans-serif"],
        "headline-lg": ["DM Sans", "sans-serif"],
        "headline-sm": ["DM Sans", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "data-md": ["JetBrains Mono", "monospace"],
        "data-lg": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "500" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "data-md": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "data-lg": ["24px", { lineHeight: "32px", fontWeight: "600" }],
      },
      keyframes: {
        "fade-in-up": {
          "0%": { opacity: "0", transform: "translateY(16px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        "fade-in-up": "fade-in-up 0.5s ease-out both",
      },
    },
  },
  plugins: [],
};